version: '2'
services:
  monoblog-app:
    image: monoblog
    environment:
      - _JAVA_OPTIONS=-Xmx512m -Xms256m
      - SPRING_PROFILES_ACTIVE=prod,swagger
      - MANAGEMENT_METRICS_EXPORT_PROMETHEUS_ENABLED=true
      - SPRING_DATASOURCE_URL=jdbc:mysql://monoblog-mysql:3306/monoblog?useUnicode=true&characterEncoding=utf8&useSSL=false
      - JHIPSTER_SLEEP=30 # gives time for other services to boot before the application
      - SPRING_DATA_JEST_URI=http://monoblog-elasticsearch:9200
      - SPRING_ELASTICSEARCH_REST_URIS=http://monoblog-elasticsearch:9200
    ports:
      - 8080:8080
  monoblog-mysql:
    extends:
      file: mysql.yml
      service: monoblog-mysql
  monoblog-elasticsearch:
    extends:
      file: elasticsearch.yml
      service: monoblog-elasticsearch
